### ISSUE TITLE
undefined method `rescue_with_handler' whit reflex action such as "click->…" or "change->…"

### ISSUE THREAD

**Issue by paulbernhard** [hopsoft/stimulus_reflex#287]
Hi,

thanks (again) for all the work on StimulusReflex. I just tried to set up a form with multiple checkboxes which will server to filter a collection of records by tags. The form is supposed to "submit" all the checked checkbox values to a reflex using the `change->Tags#set_tags` reflex method.

Though performing the `change->Tags#set_tags` when clicking on a checkbox results in a server-side error containing the following (see stacktrace below): 

```bash
[NoMethodError - undefined method `rescue_with_handler' for nil:NilClass]: /usr/local/bundle/gems/stimulus_reflex-3.2.3/lib/stimulus_reflex/channel.rb:36:in `rescue in receive'
```

Strangely, i can execute the same reflex used an a `<a href="#" data-reflex="Tags#set_tags>Test Reflex</a>` and the reflex cycle performs sucessfully but when using `click->…` on that same anchor like `<a href="#" data-reflex="click->Tags#set_tags>Test Reflex</a>` i will get that same error as above.

## To Reproduce

Without using a stimulus controller:

```erb
<%# app/views/**/filter.html.erb %>

<%# the anchor works as long as there is no "click->…" prepending the data-reflex %>
<a href="#" data-reflex="Tags#set_tags">Reflex this!</a>

<%= form_with url: "#" do |form| %>
  <% @tags.each do |tag| %>
    <%= form.check_box tag.name, 
      checked: @selected_tags.blank? || @selected_tags.include?(tag.name) ? true : false,
      data: { target: "tags-filter.checkBox", reflex: "change->Tags#set_tags" }%>
    <%= tag.name %><br>
  <% end %>
<% end %>
```

```ruby
# app/reflexes/tags_reflex.rb
class TagsReflex < ApplicationReflex
  
  def set_tags
    byebug
    puts "test me…"
  end
end
```

Or using the stimulus controller `tags-filter_controller.js`:

```erb
# app/views/**/filter.html.erb
    <div id="projects-filter" data-controller="tags-filter">

      <%# the anchor works as long as there is no "click->…" prepending the data-reflex %>
      <a href="#" data-reflex="Tags#set_tags">Reflex this!</a>

      <%= form_with url: "#" do |form| %>
        <% @tags.each do |tag| %>
          <%= form.check_box tag.name, 
            checked: @selected_tags.blank? || @selected_tags.include?(tag.name) ? true : false,
            data: { action: "change->tags-filter#submit", target: "tags-filter.checkBox" }%>
          <%= tag.name %><br>
        <% end %>
      <% end %>

      <%= render partial: "projects/project", collection: @projects, cached: true %>
    </div>
```

```js
app/javascript/controllers/tags-filter_controller.js
import { Controller } from "stimulus"
import StimulusReflex from "stimulus_reflex" 

export default class extends Controller {

  static targets = ["checkBox"]

  connect() {
    StimulusReflex.register(this)
  }

  // collect values of checked checkboxes
  // and "submit" form to reflex
  submit(event) {
    const tags = new Array()

    this.checkBoxTargets.forEach(elem => {
      console.log(elem.checked)
      if (elem.checked) { tags.push(elem.name) }
    })

    this.stimulate("Tags#set_tags", tags.join(","))
  }
}
```

## Expected behavior

The reflex should perform, pass the `tags` from the checkboxes to `TagsReflex#set_tags` and render / morph the page.

## Stacktrace

```bash
Started GET "/cable" for 172.23.0.1 at 2020-08-07 11:10:14 +0000
Cannot render console from 172.23.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Started GET "/cable/" [WebSocket] for 172.23.0.1 at 2020-08-07 11:10:14 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
StimulusReflex::Channel is transmitting the subscription confirmation
StimulusReflex::Channel is streaming from StimulusReflex::Channel
StimulusReflex::Channel#receive({"target"=>"Tags#set_tags", "args"=>[], "url"=>"http://localhost:3000/", "attrs"=>{"data-action"=>"tags-filter#submit change->stimulus-reflex#__perform", "data-target"=>"tags-filter.checkBox", "data-reflex"=>"change->Tags#set_tags", "type"=>"checkbox", "value"=>"1", "checked"=>false, "name"=>"Denkmalpflege", "id"=>"Denkmalpflege", "data-controller"=>"stimulus-reflex", "selected"=>false, "tag_name"=>"INPUT"}, "dataset"=>{"data-action"=>"tags-filter#submit change->stimulus-reflex#__perform", "data-target"=>"tags-filter.checkBox", "data-reflex"=>"change->Tags#set_tags", "data-controller"=>"stimulus-reflex"}, "selectors"=>["#projects-filter"], "reflexId"=>"84aeaf4c-0372-4de8-8586-3f5ad9aa556e", "permanent_attribute_name"=>"data-reflex-permanent", "params"=>{"authenticity_token"=>"1Ca1dlWawIcDt8nmaKuCuUgReLQ1IAZDki6HCWeMRT3YuddpxrK+zHznIJaEw2bav3frvzS6MKaxSeqXTCDTYA==", "Neubau"=>["0", "1"], "Denkmalpflege"=>["0", ""], "Bier"=>["0", "1"], "Pina Colada"=>["0", "1"]}})
Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"StimulusReflex::Channel\"}", "data"=>"{\"target\":\"Tags#set_tags\",\"args\":[],\"url\":\"http://localhost:3000/\",\"attrs\":{\"data-action\":\"tags-filter#submit change->stimulus-reflex#__perform\",\"data-target\":\"tags-filter.checkBox\",\"data-reflex\":\"change->Tags#set_tags\",\"type\":\"checkbox\",\"value\":\"1\",\"checked\":false,\"name\":\"Denkmalpflege\",\"id\":\"Denkmalpflege\",\"data-controller\":\"stimulus-reflex\",\"selected\":false,\"tag_name\":\"INPUT\"},\"dataset\":{\"data-action\":\"tags-filter#submit change->stimulus-reflex#__perform\",\"data-target\":\"tags-filter.checkBox\",\"data-reflex\":\"change->Tags#set_tags\",\"data-controller\":\"stimulus-reflex\"},\"selectors\":[\"#projects-filter\"],\"reflexId\":\"84aeaf4c-0372-4de8-8586-3f5ad9aa556e\",\"permanent_attribute_name\":\"data-reflex-permanent\",\"params\":{\"authenticity_token\":\"1Ca1dlWawIcDt8nmaKuCuUgReLQ1IAZDki6HCWeMRT3YuddpxrK+zHznIJaEw2bav3frvzS6MKaxSeqXTCDTYA==\",\"Neubau\":[\"0\",\"1\"],\"Denkmalpflege\":[\"0\",\"\"],\"Bier\":[\"0\",\"1\"],\"Pina Colada\":[\"0\",\"1\"]}}"}) [NoMethodError - undefined method `rescue_with_handler' for nil:NilClass]: /usr/local/bundle/gems/stimulus_reflex-3.2.3/lib/stimulus_reflex/channel.rb:36:in `rescue in receive' | /usr/local/bundle/gems/stimulus_reflex-3.2.3/lib/stimulus_reflex/channel.rb:31:in `receive' | /usr/local/bundle/gems/actioncable-6.0.3.2/lib/action_cable/channel/base.rb:268:in `public_send' | /usr/local/bundle/gems/actioncable-6.0.3.2/lib/action_cable/channel/base.rb:268:in `dispatch_action' | /usr/local/bundle/gems/actioncable-6.0.3.2/lib/action_cable/channel/base.rb:170:in `block in perform_action'
```

### StimulusReflex

- Gem: 3.2.3
- Node package: ^3.3.0-pre2

### External tools

- Ruby: 2.7.1
- Rails: 6.0.3.2
- Node: 12

### Browser

- Browser Firefox
- Version 79.0

Thanks and best,
Paul

**Comment by uurcank** [comment]
there should be a syntax error somewhere. try changing controller file name to "tags_filter_controller.js" from "tags-filter_controller.js"

**Comment by RolandStuder** [comment]
If you don't say which event should trigger a reflex, nothing will. Unlike stimulusjs, where you have default events to trigger an action like `<button data-action="controller#doStuff">`. Stimulus Reflex needs an explcit trigger event like `data-reflex="click->controller#doSomething`

So this has nothing todo with the server error. Except if you ommit the `click->` it will never trigger anything.

So I think the problem lies elsewhere. But first it would be best to make sure, the Gem and the Node package are on the same version.

Could you try this? Otherwise if you can invite me to the repo, I would be happy to see what's going on there.

**Comment by leastbad** [comment]
Nice catch, @RolandStuder.

**Comment by paulbernhard** [comment]
Hi, thanks for the replies. I rewrote the whole thing from scratch using a different controller file name `filter_controller.js` instead of `tags-filter_controller.js`, thus `data-controller="change->filter#tags"`, …, and now it works. I couldn't tell what the problem was besides the change of the filename. Below is the updated working code.

Besides, @RolandStuder thanks for the update on the mandatory action names in stimulus reflex unlike stimulusjs.

`view.html.erb`:

```erb
<%= form_with url: "#" do |form| %>
  <ul>
    <li>
      <%= form.label "_none" do %>
        <%= form.check_box "_none", data: { target: "filter.input", action: "change->filter#tags", value: nil }, 
          checked: selected_tags.blank? %>Alle Projekte
      <% end %>
    </li>

    <% tags.each do |tag| %>
      <li>
        <%= form.label tag.name do %>
          <%= form.check_box tag.name, data: { target: "filter.input", action: "change->filter#tags", value: tag.name }, 
            checked: !selected_tags.blank? && selected_tags.include?(tag.name) %><%= tag.name %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
```

`app/javascript/controllers/filter_controller.js`:

```js
import ApplicationController from "./application_controller"

export default class extends ApplicationController {

  static targets = ["input", "results", "spinner"]

  tags(event) {
    event.preventDefault()
    // …
    this.stimulate("Filter#tags", tags)
  }

  beforeTags(elem, reflex) {
    // …
  }

  // remove spinner and show direct children
  tagsSuccess(elem, reflex) {
    // …
  }
}
```

`app/reflexes/filter_reflex.rb`:

```ruby
class FilterReflex < ApplicationReflex
  
  def tags(tags = nil)
    @selected_tags = tags
  end
end
```

Thanks for the help, have a good day,
Paul

**Comment by leastbad** [comment]
In the future, please consider posting an MVCE that we can run on our local machines. It's possible that we could have been much more helpful, sooner.

Also, while the Stimulus site does suggest that either `_` and `-` are acceptable for file naming, there's a strong convention in the community for using `_` and the document does not suggest that you can use *both* in the same filename.

Either way, congrats on getting it working!
