### ISSUE TITLE
uninitialized constant StimulusReflex::Channel

### ISSUE THREAD

**Issue by scottbarrow** [hopsoft/stimulus_reflex#408]
# Bug Report

_Please help us help you by filling out any applicable information in this template and removing the rest!_

## Describe the bug
CI build fails 

rake aborted!
--
  | NameError: uninitialized constant StimulusReflex::Channel
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
  | /usr/local/bundle/gems/stimulus_reflex_testing-0.1.0/lib/stimulus_reflex/test_case.rb:6:in `<class:TestChannel>'
  | /usr/local/bundle/gems/stimulus_reflex_testing-0.1.0/lib/stimulus_reflex/test_case.rb:5:in `<class:TestCase>'
  | /usr/local/bundle/gems/stimulus_reflex_testing-0.1.0/lib/stimulus_reflex/test_case.rb:4:in `<main>'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  | /usr/local/bundle/gems/skylight-core-4.3.1/lib/skylight/core/probes.rb:118:in `require'
  | /usr/local/bundle/gems/stimulus_reflex_testing-0.1.0/lib/stimulus_reflex_testing.rb:2:in `<main>'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  | /app/config/application.rb:21:in `<top (required)>'
  | /app/Rakefile:2:in `require_relative'
  | /app/Rakefile:2:in `<top (required)>'
  | /usr/local/bundle/bin/bundle:23:in `load'
  | /usr/local/bundle/bin/bundle:23:in `<main>'
  |  
  | Caused by:
  | NameError: uninitialized constant StimulusReflex::Channel
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
  | /usr/local/bundle/gems/stimulus_reflex_testing-0.1.0/lib/stimulus_reflex/test_case.rb:6:in `<class:TestChannel>'
  | /usr/local/bundle/gems/stimulus_reflex_testing-0.1.0/lib/stimulus_reflex/test_case.rb:5:in `<class:TestCase>'
  | /usr/local/bundle/gems/stimulus_reflex_testing-0.1.0/lib/stimulus_reflex/test_case.rb:4:in `<main>'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  | /usr/local/bundle/gems/skylight-core-4.3.1/lib/skylight/core/probes.rb:118:in `require'
  | /usr/local/bundle/gems/stimulus_reflex_testing-0.1.0/lib/stimulus_reflex_testing.rb:2:in `<main>'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  | /usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  | /app/config/application.rb:21:in `<top (required)>'
  | /app/Rakefile:2:in `require_relative'
  | /app/Rakefile:2:in `<top (required)>'
  | /usr/local/bundle/bin/bundle:23:in `load'
  | /usr/local/bundle/bin/bundle:23:in `<main>'
  | (See full trace by running task with --trace)

## To Reproduce

Steps to reproduce the behavior

## Screenshots or reproduction

If applicable, add screenshots (errors, example of the behavior, etc.) to help explain your problem or post a link to a repository that replicates the issue.

### StimulusReflex

- Gem: [e.g. 3.4.0.pre9]
- Node package: [e.g. 2.0.1]

### External tools

- Ruby: [e.g. 2.6.4]
- Rails: [e.g. 6.0.0]
- Node: [e.g. 12.4.0]

**Comment by scottbarrow** [comment]
Related https://github.com/podia/stimulus_reflex_testing/issues/6
